blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/yinnho/UPnPCast/blob/master/README.md
    about: Check the documentation for usage examples and API reference
  - name: 🎯 Demo App
    url: https://github.com/yinnho/UPnPCast/tree/master/app-demo
    about: Look at the demo app for complete examples
  - name: 💬 Discussions
    url: https://github.com/yinnho/UPnPCast/discussions
    about: Ask questions and discuss ideas with the community 